POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNhcnJvdCIsImlkIjoiNWY0MWM5MDQ1MDlhOTQyOGUzZWUzNzAzIiwiaWF0IjoxNTk4MTcwNzMxfQ.E7s-HmTqEZ0Brhfty7hd23ukDZZ6NICCBe0omIXAPCY

{
  "title": "Growing Plants the Right Way pt. 4",
  "author": "Green Thumbs",
  "url": "plants.com",
  "likes": 8888,
  "userId": "5f41c904509a9428e3ee3703"
}